kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: edos-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      # TeaStore WebUI
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Grafana
      - containerPort: 30030
        hostPort: 3000
        protocol: TCP
      # Prometheus
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
